### ISSUE TITLE
Select all needed

### ISSUE THREAD

**Issue by cordeosdev** [reneeb/otrs-CustomerUserCheckAndDelete#1]
This is a really great, useful OTRS package we REALLY appreciate... but its hard to use without a 'select all' function since you need to click each individual user to delete. 

As a work-around, we changed this code to reverse the selection - defaults to all selected and unselect those you dont want to delete. Line 60 of Custom/Kernel/Output/HTML/Templates/Standard/AdminCustomerUserCheckAndDelete.tt
to
<input type="checkbox" value="[% Data.UserLogin | html %]" name="CustomerID" **_checked_**/>

Thanks for this useful package!

**Comment by reneeb** [comment]
That sounds like a good idea... I will work on that next week.

**Comment by reneeb** [comment]
The newes version has a select all functionality...
